name: 'actions-setup-bazel'
description: 'Setup the bazel build tool'
inputs:
  bazel-version:
    description: 'The version of bazel to setup. E.g. 2.0.0'
    default: '2.0'
  github-api-token:
    description: 'Authentication token to use when connecting to the GitHub API'
    default: '${{ github.token }}'
runs:
  using: 'node16'
  main: 'dist/index.js'
